# Generated by Django 6.0.7 on 2026-07-22 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guide_number", models.CharField(max_length=50, unique=True)),
                ("customer", models.CharField(max_length=100)),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Creado"),
                            ("PICKED_UP", "Recogido"),
                            ("IN_TRANSIT", "En tránsito"),
                            ("OUT_FOR_DELIVERY", "En reparto"),
                            ("RETURNED", "Devuelto"),
                            ("DELIVERED", "Entregado"),
                        ],
                        default="CREATED",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=30)),
                ("location", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="shipments.shipment",
                    ),
                ),
            ],
        ),
    ]
